### ISSUE TITLE
win-spawn deprecated

### ISSUE THREAD

**Issue by kentcdodds** [bahmutov/npm-utils#19]
When installing [copi](npm.im/copi), I got this error: 

> npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.

Just FYI :-)

**Comment by bahmutov** [comment]
yeah, just saw this, it is new
