### ISSUE TITLE
Support Scoped Registries

### ISSUE THREAD

**Issue by destroyerofbuilds** [bahmutov/npm-utils#26]
`registry-url.js` only retrieves the value of `registry`, which means that it will always append the `_authToken` to the value of `registry`. Therefore, scoped registries in the `.npmrc` configuration file, such as `@company:registry`, are not supported.

In my use case I have an `.npmrc` configuration file with two registries in it:

```
registry = "internal mirror of public registry"
@company:registry = "private registry"
```

The project's `package.json` file has set `publishConfig` to publish to the scoped, `@company`, registry. The project's name is `@company/something`.

In my case, I believe the value of the environment variable `NPM_TOKEN` needs to be appended to `@company:registry` instead of `registry` to allow proper authentication when publishing the project.

If you have access to the project's name, you can call something like [registry-url](https://www.npmjs.com/package/registry-url) to get the appropriate scoped registry.

An example of how `registry-url` is used can be seen in [package-json](https://github.com/sindresorhus/package-json/blob/master/index.js#L10).

**Comment by bahmutov** [comment]
if you could implement a change and submit a pull request, I would be happy to merge it,
it is an important missing feature

**Comment by hbetts** [comment]
@bahmutov I'll see if I can implement this enhancement in the next week, though no promises.

**Comment by hbetts** [comment]
@bahmutov thank you for incorporating the scoped registry support.

I'm sorry I dropped off the radar there for a while, but I was gone for a week on a business trip.

**Comment by bahmutov** [comment]
no problem, hope this change is useful to gitlab release
