### ISSUE TITLE
Auth token is being set for the wrong registry? 

### ISSUE THREAD

**Issue by kachkaev** [bahmutov/npm-utils#33]
Hi Gleb,

I'm not 100% sure, but there is a change that I've faced a small issue in your repo. Please follow the discussion here: https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/9

To summarise, it seems that `npm-utils` ignores `registry` from `publishConfig` in `package.json` and authenticates in a wrong repo. This happens when `semantic-release-gitlab` is trying to publish a release.

How relevant could this be to `npm-utils`? Or should your lib just be used somehow else in the situation mentioned?

Cheers,
Alex

**Comment by hbetts** [comment]
We may want to change line [37](https://github.com/bahmutov/npm-utils/blob/master/src/set-auth-token.js#L37) to something like:

```javascript
var registry = getPackage(process.cwd()).packageConfig && getPackage(process.cwd()).packageConfig.registry ?
  getPackage(process.cwd()).packageConfig.registry :
  registryUrl(scope);
```

**Comment by hbetts** [comment]
@bahmutov if my proposed change is acceptable I can submit a pull request for it. It may need to be a major version to account for how the `packageConfig` property would take precedence over the results of `registryUrl`.

**Comment by canercandan** [comment]
@hbetts @bahmutov +1 to have this change

**Comment by bahmutov** [comment]
@hbetts looks like a reasonable change - and I am ok with bumping major change for this
