### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by svnlto** [bahmutov/npm-utils#40]
Update readme references to `.npmrc`. Explain that it now looks for a local file first before defaulting to `~/.npmrc`. 

Related: https://github.com/bahmutov/npm-utils/pull/39

**Comment by bahmutov** [comment]
Version `1.14.0` has been published to NPM. The full release note can be found at [npm-utils/releases/tag/v1.14.0](https://github.com/bahmutov/npm-utils/releases/tag/v1.14.0).

**Tip:** safely upgrade dependency npm-utils in your project using [next-update](https://github.com/bahmutov/next-update)
