### ISSUE TITLE
Error: Cannot find module '/npm-prune'

### ISSUE THREAD

**Issue by hbetts** [bahmutov/npm-utils#44]
I'm filing this issue on behalf of a report filed against `npm-publish-git-tag` - https://gitlab.com/hyper-expanse/npm-publish-git-tag/issues/3

There's a minor typo introduced in the following commit - f193b40527ad77671bdf28b40a254982f95975f6

`require('/npm-prune')` should be `require('./npm-prune')`

**Comment by bahmutov** [comment]
Hahaha, that's what I get for skipping the tests! Thanks @hbetts - BTW did you like `github-post-release`?

**Comment by bahmutov** [comment]
fix pushed

**Comment by hbetts** [comment]
> BTW did you like `github-post-release`

I hadn't quite had an opportunity to look at `github-post-release` in detail until today.

On seeing your documentation example, I definitely want to update my project to include a reference to the full changelog (especially now that I'm encouraging those not comfortable with a release-per-commit to use scheduled releases; a scenario where a single release may contain a large number of individual changes).

I've honestly been trying to decide whether I can incorporate `github-post-release` into my future plans. In the coming months I'll need a semantic release tool capable of supporting GitHub and an unknown CI platform, but I don't know whether `semantic-release` is suitable for my needs (Its maintainers have been very busy with other projects, leaving `semantic-release`, at this time, unmaintained. Furthermore, `semantic-release` is hard-coded against Travis CI, which means that to use any other CI platform, intervention is required by each `semantic-release` consuming project)

Yet writing my own `semantic-release-github` project may mean duplicating the work you've already done.
