### ISSUE TITLE
`local-or-home-npmrc` Breaks Node 4 For Yarn Users

### ISSUE THREAD

**Issue by hbetts** [bahmutov/npm-utils#45]
`local-or-home-npmrc` sets the value for `node` in the `engines` property of their `package.json` file to [node 6](https://github.com/svnlto/local-or-home-npmrc/blob/master/package.json#L13).

Yarn will fail during the installation process if the value of the `engines` property does not match against the version of Node used to run Yarn - https://github.com/yarnpkg/rfcs/pull/69#issuecomment-308567694

Therefore, `npm-utils`, version 1.x, was working for Node 4 Yarn users until `local-or-home-npmrc` was introduced in version 1.13.0, but now `npm-utils`, though more specifically `local-or-home-npmrc`, can't be installed.

I ran into this yesterday when I upgraded my Yarn lockfile, and ran my build (which runs against all supported versions of Node, npm, and Yarn) - https://gitlab.com/hyper-expanse/semantic-release-gitlab-notifier/-/jobs/22286197

```
error local-or-home-npmrc@0.0.0-development: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
```

I'll probably consider locking down the `npm-utils` version in my project's `package.json` file as a temporary way to work around the issue.

However, as I still support all Node LTS versions, including Node 4, I'll need to consider a longer-term solution (I do want my downstream consumers to benefit from the features you've been adding to `npm-utils`, but still be able to use Node 4 is that happens to be their current situation)

Do you have any thoughts, or suggestions, on the matter?

**Comment by bahmutov** [comment]
Since I use my fork I can do this quickly ;) https://github.com/bahmutov/local-or-home-npmrc already relaxed it to Node 4

**Comment by hbetts** [comment]
@bahmutov, thank you for your quick response, and fix.

My Yarn tests on Node 4 are now passing again (after I updated my lock files).

**Comment by hbetts** [comment]
Since `npm-utils` is now setup so that it can be installed on Node 4 with Yarn, I'm not sure how you want to handle this issue. I assume you eventually want to switch back to the upstream project after your lazy function pull request is accepted. In that case, should this remain open as a reminder that this issue will also need to be addressed upstream?

**Comment by bahmutov** [comment]
sure. BTW @hbetts do you want to chat sometime? I have ideas about general purpose "semantic" tool which might overlap with your interests too.

**Comment by hbetts** [comment]
@bahmutov, yes, definitely. Please feel free to reach out to me via my personal e-mail, or you can find me lurking on gitter.im.

**Comment by svnlto** [comment]
I think we can close this now, given https://github.com/svnlto/local-or-home-npmrc/commit/492179753b1250f4d7895137f1398a390eed6f10 is now merged and released.

Thanks again @bahmutov

**Comment by bahmutov** [comment]
Closing for now
